Search.appendIndex(
    [
                {
            "fqsen": "\\Controlador",
            "name": "Controlador",
            "summary": "Clase\u0020Controlador",
            "url": "classes/Controlador.html"
        },                {
            "fqsen": "\\Controlador\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020de\u0020la\u0020clase\u0020Controlador",
            "url": "classes/Controlador.html#method___construct"
        },                {
            "fqsen": "\\Controlador\u003A\u003Alistar\u0028\u0029",
            "name": "listar",
            "summary": "Lista\u0020todos\u0020los\u0020art\u00EDculos\u0020del\u0020cat\u00E1logo",
            "url": "classes/Controlador.html#method_listar"
        },                {
            "fqsen": "\\Controlador\u003A\u003Adetalle\u0028\u0029",
            "name": "detalle",
            "summary": "Obtiene\u0020el\u0020detalle\u0020de\u0020un\u0020art\u00EDculo\u0020espec\u00EDfico",
            "url": "classes/Controlador.html#method_detalle"
        },                {
            "fqsen": "\\Controlador\u003A\u003A\u0024modelo",
            "name": "modelo",
            "summary": "",
            "url": "classes/Controlador.html#property_modelo"
        },                {
            "fqsen": "\\ControladorSugerencias",
            "name": "ControladorSugerencias",
            "summary": "Clase\u0020ControladorSugerencias",
            "url": "classes/ControladorSugerencias.html"
        },                {
            "fqsen": "\\ControladorSugerencias\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020de\u0020la\u0020clase\u0020ControladorSugerencias",
            "url": "classes/ControladorSugerencias.html#method___construct"
        },                {
            "fqsen": "\\ControladorSugerencias\u003A\u003AguardarSugerencia\u0028\u0029",
            "name": "guardarSugerencia",
            "summary": "Guarda\u0020una\u0020nueva\u0020sugerencia\u0020en\u0020la\u0020sesi\u00F3n",
            "url": "classes/ControladorSugerencias.html#method_guardarSugerencia"
        },                {
            "fqsen": "\\ControladorSugerencias\u003A\u003AobtenerSugerencias\u0028\u0029",
            "name": "obtenerSugerencias",
            "summary": "Obtiene\u0020todas\u0020las\u0020sugerencias\u0020almacenadas\u0020en\u0020sesi\u00F3n",
            "url": "classes/ControladorSugerencias.html#method_obtenerSugerencias"
        },                {
            "fqsen": "\\ControladorSugerencias\u003A\u003A\u0024sugerencias",
            "name": "sugerencias",
            "summary": "",
            "url": "classes/ControladorSugerencias.html#property_sugerencias"
        },                {
            "fqsen": "\\ControladorRegistro",
            "name": "ControladorRegistro",
            "summary": "Clase\u0020ControladorRegistro",
            "url": "classes/ControladorRegistro.html"
        },                {
            "fqsen": "\\ControladorRegistro\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020de\u0020la\u0020clase\u0020ControladorRegistro",
            "url": "classes/ControladorRegistro.html#method___construct"
        },                {
            "fqsen": "\\ControladorRegistro\u003A\u003AguardarUsuario\u0028\u0029",
            "name": "guardarUsuario",
            "summary": "Guarda\u0020un\u0020nuevo\u0020usuario\u0020en\u0020la\u0020sesi\u00F3n",
            "url": "classes/ControladorRegistro.html#method_guardarUsuario"
        },                {
            "fqsen": "\\CON_CONTROLADOR",
            "name": "CON_CONTROLADOR",
            "summary": "",
            "url": "namespaces/default.html#constant_CON_CONTROLADOR"
        },                {
            "fqsen": "\\Modelo",
            "name": "Modelo",
            "summary": "Clase\u0020Modelo",
            "url": "classes/Modelo.html"
        },                {
            "fqsen": "\\Modelo\u003A\u003AobtenerTodos\u0028\u0029",
            "name": "obtenerTodos",
            "summary": "Obtiene\u0020todos\u0020los\u0020art\u00EDculos\u0020del\u0020cat\u00E1logo",
            "url": "classes/Modelo.html#method_obtenerTodos"
        },                {
            "fqsen": "\\Modelo\u003A\u003AobtenerPorId\u0028\u0029",
            "name": "obtenerPorId",
            "summary": "Obtiene\u0020un\u0020art\u00EDculo\u0020espec\u00EDfico\u0020por\u0020su\u0020ID",
            "url": "classes/Modelo.html#method_obtenerPorId"
        },                {
            "fqsen": "\\Modelo\u003A\u003A\u0024articulos",
            "name": "articulos",
            "summary": "",
            "url": "classes/Modelo.html#property_articulos"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
